### ISSUE TITLE
In the absence of minerva.local.cfg default to minerva.dist.cfg

### ISSUE THREAD

**Issue by kotfic** [Kitware/minerva#168]
Currently we just crash

```
Loaded plugin "gravatar"
Loaded plugin "jobs"
WARNING: No description docs present for route POST item/romanesco/:inputType/:inputFormat/:outputFormat
WARNING: No description docs present for route GET item/:itemId/romanesco/:inputType/:inputFormat/:outputFormat
WARNING: No description docs present for route DELETE item/:itemId/romanesco/:jobId
Loaded plugin "romanesco"
ERROR: Failed to load plugin "minerva":
Traceback (most recent call last):
  File "/home/kotfic/kitware/projects/NEX/src/girder/girder/girder/utility/plugin_utilities.py", line 80, in loadPlugins
    plugin, root, appconf, apiRoot, curConfig=curConfig)
  File "/home/kotfic/kitware/projects/NEX/src/girder/girder/girder/utility/plugin_utilities.py", line 143, in loadPlugin
    module = imp.load_module(moduleName, fp, pathname, description)
  File "/home/kotfic/kitware/projects/NEX/src/girder/girder/plugins/minerva/server/__init__.py", line 28, in <module>
    _mergeConfig(os.path.join(PACKAGE_DIR, 'conf', f))
  File "/home/kotfic/kitware/projects/NEX/src/girder/girder/girder/utility/config.py", line 32, in _mergeConfig
    cherrypy._cpconfig.merge(cherrypy.config, filename)
  File "/home/kotfic/.venvs/NEX/lib/python2.7/site-packages/cherrypy/_cpconfig.py", line 139, in merge
    for section, value_map in reprconf.as_dict(other).items():
  File "/home/kotfic/.venvs/NEX/lib/python2.7/site-packages/cherrypy/lib/reprconf.py", line 51, in as_dict
    config = Parser().dict_from_file(config)
  File "/home/kotfic/.venvs/NEX/lib/python2.7/site-packages/cherrypy/lib/reprconf.py", line 232, in dict_from_file
    self.read(file)
  File "/home/kotfic/.venvs/NEX/lib/python2.7/site-packages/cherrypy/lib/reprconf.py", line 202, in read
    fp = open(filename)
IOError: [Errno 2] No such file or directory: '/home/kotfic/kitware/projects/NEX/src/girder/girder/plugins/minerva/server/conf/minerva.local.cfg'

```

**Comment by mgrauer** [comment]
Also update the [note in the installation docs](https://github.com/Kitware/minerva/blob/master/docs/installation.rst#install-of-minerva-as-a-girder-plugin) to say that we will fall back to the dist absent the local.
