### ISSUE TITLE
Romanesco plugin directory does not exists

### ISSUE THREAD

**Issue by aashish24** [Kitware/minerva#169]
I checked out current master and followed instructions in RTD. Ran into this issue: 

```code
Traceback (most recent call last):
  File "/home/chaudhary/tools/minerva/src.git/girder/utility/plugin_utilities.py", line 80, in loadPlugins
    plugin, root, appconf, apiRoot, curConfig=curConfig)
  File "/home/chaudhary/tools/minerva/src.git/girder/utility/plugin_utilities.py", line 122, in loadPlugin
    pluginParentDir = getPluginParentDir(name, curConfig)
  File "/home/chaudhary/tools/minerva/src.git/girder/utility/plugin_utilities.py", line 104, in getPluginParentDir
    raise Exception('Plugin directory %s does not exist' % name)
Exception: Plugin directory romanesco does not exist
```

**Comment by danlamanna** [comment]
What step produced this?

**Comment by aashish24** [comment]
Just running girder master with minerva plugin
```code
python girder
```
